name: Release

on:
  push:
    branches:
      - main

jobs:
  version:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v14
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Install direnv-nix
        run: nix shell nixpkgs#direnv -c direnv allow .

      - name: Setup
        run: pnpm run setup

      - name: Setup git user
        run: git-user:setup

      - name: Create Release Pull Request or Publish to npm
        # https://github.com/changesets/action
        uses: changesets/action@v1
        with:
          version: pnpm run version
          commit: 'chore: update versions'
          title: 'chore: update versions'
          # this expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

