name: ReleaseBin

on:
  push:
    tags:
      - 'yakite-toast*'

jobs:
  upload:
    runs-on: macos-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Verify Nix Installation
        run: nix shell nixpkgs#nix-info -c nix-info -m

      - name: Install Direnv With Nix
        uses: aldoborrero/direnv-nix-action@v2
        with:
          use_nix_profile: true
          nix_channel: nixpkgs

      - name: Load PATH Changes
        run: direnv exec . sh -c 'echo $PATH' > "$GITHUB_PATH"
      - name: Load other environment changes
        run: direnv export gha >> "$GITHUB_ENV"

      - name: Build
        run: yakite-toast:build


      - name: Upload Binaries To Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./apps/yakite-toast/dist/yakite-toast
          asset_name: yakite-toast
          tag: ${{ github.ref }}
